//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbAudit
    {
        public long AuditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string TableName { get; set; }
        public string UserName { get; set; }
        public string Ip { get; set; }
        public string Action { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public string ChangedColumns { get; set; }
    }
}
